version: '3.7'

services:
  beacon-server:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_cloud.sh
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
      - /beacon/speed_test:/beacon/speed_test
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=cloud
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=beacon-redis_redis-server_15379_1
      - GLOBAL_REDIS_PORT=6379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=tdydalned1001.sl.bluecloud.ibm.com
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://tdydalned1001.sl.bluecloud.ibm.com:8443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=tdydalned1001_1
      - ENV=cloud
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
    networks:
      - default

  beacon-server2:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_cloud.sh
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
      - /beacon/speed_test:/beacon/speed_test
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=cloud
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=beacon-redis_redis-server_15379_1
      - GLOBAL_REDIS_PORT=6379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=tdydalned1001.sl.bluecloud.ibm.com
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://tdydalned1001.sl.bluecloud.ibm.com:8443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=tdydalned1001_2
      - ENV=cloud
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
    networks:
      - default

  beacon-server-backend:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_cloud.sh
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
      - /beacon/speed_test:/beacon/speed_test
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=cloud
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=beacon-redis_redis-server_15379_1
      - GLOBAL_REDIS_PORT=6379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=tdydalned1001.sl.bluecloud.ibm.com
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://tdydalned1001.sl.bluecloud.ibm.com:8443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=tdydalned1001_1
      - ENV=cloud
      - PERMISSION_CONTROL=False
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
    networks:
      - default

networks:
  default:
    external:
      name: beacon_network