version: '3.7'

services:
  beacon-server:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_dev.sh
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: dev.beacon_server.docker_logs
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
      - /beacon/speed_test:/beacon/speed_test
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=9.181.48.101
      - GLOBAL_REDIS_PORT=15379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=9.181.48.101
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://beacon.cn.ibm.com:18443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=ned101_1
      - ENV=dev
      - PERMISSION_CONTROL=True
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
      - EMAIL_SENDER_QUEUE=dev-system-high
      - EMAIL_SENDER_DISPLAY_NAME=system-script/email_sender/email_sender
      - ROUTINE_HIGH_QUEUE=dev-routine-high
      - SYSTEM_HIGH_QUEUE=dev-system-high
      - ES_SERVER=9.94.82.30:9200,9.94.82.30:9201,9.94.82.30:9202
    networks:
      - default

  beacon-server2:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_dev.sh
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: dev.beacon_server.docker_logs
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /beacon/speed_test:/beacon/speed_test
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=9.181.48.101
      - GLOBAL_REDIS_PORT=15379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=9.181.48.101
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://beacon.cn.ibm.com:18443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=ned101_2
      - ENV=dev
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
      - EMAIL_SENDER_QUEUE=dev-system-high
      - EMAIL_SENDER_DISPLAY_NAME=system-script/email_sender/email_sender
      - ROUTINE_HIGH_QUEUE=dev-routine-high
      - SYSTEM_HIGH_QUEUE=dev-system-high
      - ES_SERVER=9.94.82.30:9200,9.94.82.30:9201,9.94.82.30:9202
    networks:
      - default

  beacon-server-backend:
    build: ../
    restart: always
    command: sh /beacon-server/entrypoint/entrypoint_backend.sh
    volumes:
      - ../../beacon-server:/beacon-server
      - /beacon/client:/beacon/client/
      - /beacon/files:/beacon/files
      - /beacon/files_user:/beacon/files_user
      - /excel_file/data_schema:/tmp/excel_file/data_schema
      - /excel_file/export_files:/tmp/excel_file/export_files
      - /beacon/speed_test:/beacon/speed_test
#    ports:
#      - 8000:8000
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - PORT=8000
      - GLOBAL_REDIS_HOST=9.181.48.101
      - GLOBAL_REDIS_PORT=15379
      - GLOBAL_REDIS_INIT_DB=0
      - GLOBAL_REDIS_SCHEMA_DB=0
      - GLOBAL_REDIS_DATA_DB=0
      - LOG_STASH_HOST=9.111.147.175
      - LOG_STASH_PORT=5000
      - PROJECT_INSTANCE=dev-ned106
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - LOG_FILE=/beacon-server/logs/beacon-server.log
      - GLOBAL_RABBITMQ_HOST=9.181.48.101
      - GLOBAL_RABBITMQ_PORT=25672
      - API_HOST=https://beacon.cn.ibm.com:18443
      - AGENT_INSTALL_LOCATION=/beacon/client
      - AES_KEY=/beacon-server/certificates/beacon.key
      - UPLOAD_FILE_PATH=/beacon/files
      - USER_UPLOAD_FILE_PATH=/beacon/files_user
      - NGINX_BACKEND_ID=ned101_1
      - ENV=dev
      - PERMISSION_CONTROL=False
      - SPEED_TEST_FILE_PATH=/beacon/speed_test
      - EMAIL_SENDER_QUEUE=dev-system-high
      - EMAIL_SENDER_DISPLAY_NAME=system-script/email_sender/email_sender
      - ROUTINE_HIGH_QUEUE=dev-routine-high
      - SYSTEM_HIGH_QUEUE=dev-system-high
      - ES_SERVER=9.94.82.30:9200,9.94.82.30:9201,9.94.82.30:9202
    networks:
      - backend

networks:
  default:
    external:
      name: beacon_network

  backend:
    external:
      name: backend_network
